name: ciacat
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: 5.4.0
  firebase_auth: ^5.0.0  # ou a versão mais recente
  firebase_core: ^3.4.0
  shared_preferences: ^2.0.8
  firebase_analytics: ^11.3.0
   # Outros pacotes
  clipboard: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
